{% set name = "pytsql" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytsql-{{ version }}.tar.gz
  sha256: 383550b7e621006a2156c67e09b66c9228484a5d45e4c5a3947f4059ff9a17f2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - antlr4-python3-runtime =4.11.1
    - pyodbc >=4.0.30
    - python
    - sqlalchemy >=1.4

test:
  imports:
    - pytsql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytsql/
  summary: pytsql allows to run mssql scripts, typically run via GUIs, via CLI.
  dev_url: https://github.com/quantco/pytsql
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
    - ivergara
    - kklein
