{% set name = "pytsql" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytsql-{{ version }}.tar.gz
  sha256: 76c0c4751e091d32c21aba95e7293d077cf365ed3cebfc64afb219220f293c71

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - antlr4-python3-runtime >=4.10,<4.14
    - pyodbc >=4.0.30
    - python
    - sqlalchemy >=1.4
    - click

test:
  imports:
    - pytsql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytsql/
  summary: pytsql allows to run mssql scripts, typically run via GUIs, via CLI.
  dev_url: https://github.com/quantco/pytsql
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
    - ivergara
    - kklein
